Repository hpi-swt2/compass-portal-blue, pull requests merged in 2021-12, with the labels that each got.

#27 Add (indoor) maps route
  app/assets/stylesheets/map.scss
  app/controllers/map_controller.rb
  app/helpers/map_helper.rb
  app/views/layouts/_navbar.html.erb
  app/views/map/index.html.erb
  config/routes.rb
  spec/requests/map_spec.rb
Labels: HG

#36 Feature/hg 21 seeing indoor map
  app/views/layouts/application.html.erb
  app/views/map/index.html.erb
Labels: HG

#28 Feature/apmw 7 user data model
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/assets/images/default-profile-picture.png
  app/controllers/application_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/models/room.rb
  app/models/user.rb
  config/initializers/phonelib.rb
  db/migrate/20211125131719_add_additional_fields_to_user.rb
  db/migrate/20211125143735_create_active_storage_tables.active_storage.rb
  db/migrate/20211129154052_create_join_table_room_user.rb
  db/schema.rb
  spec/factories/rooms.rb
  spec/models/room_spec.rb
  spec/views/rooms/edit.html.erb_spec.rb
  spec/views/rooms/index.html.erb_spec.rb
  spec/views/rooms/show.html.erb_spec.rb
Labels: APMW

#41 Feature/cmjd 11 search bar
  app/assets/stylesheets/_colors.scss
  app/assets/stylesheets/search_results.scss
  app/controllers/search_results_controller.rb
  app/helpers/search_results_helper.rb
  app/models/search_result.rb
  app/views/search_results/_search_result.json.jbuilder
  app/views/search_results/index.html.erb
  app/views/search_results/index.json.jbuilder
  app/views/welcome/index.html.erb
  config/routes.rb
  spec/factories/search_results.rb
  spec/features/home_spec.rb
  spec/helpers/search_results_helper_spec.rb
  spec/models/search_result_spec.rb
  spec/requests/search_results_spec.rb
  spec/routing/search_results_routing_spec.rb
  spec/views/search_results/index.html.erb_spec.rb
Labels: CMJD

#39 Feature/rh 19 show page
  app/assets/stylesheets/users.scss
  app/controllers/users_controller.rb
  app/helpers/users_helper.rb
  app/views/devise/registrations/edit.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  spec/factories/users.rb
  spec/features/users/user_show_page_spec.rb
  spec/helpers/users_helper_spec.rb
  spec/requests/users_spec.rb
Labels: RH

#45 Feature/rh 16 UI for user data editing
  app/controllers/application_controller.rb
  app/controllers/openingtimes_controller.rb
  app/javascript/packs/application.js
  app/models/user.rb
  app/views/devise/registrations/edit.html.erb
  app/views/openingtimes/_form.html.erb
  app/views/rooms/_form.html.erb
  spec/features/users/edit_user_details_spec.rb
Labels: RH

#40 Adds ability to place a marker on the map (Fix #22)
  app/views/map/index.html.erb
Labels: HG

#38 Feature/rh 17 UI for user profile picture
  app/assets/images/default-profile-picture.old.png
  app/assets/images/default-profile-picture.png
  app/assets/stylesheets/devise.scss
  app/controllers/application_controller.rb
  app/javascript/packs/application.js
  app/views/devise/registrations/edit.html.erb
  app/views/users/show.html.erb
  spec/features/users/edit_user_details_spec.rb
Labels: RH

#84 Feature/tobias #49 show path on map & #48 calculate shortest path
  Gemfile
  Gemfile.lock
  app/assets/constants/buildings.rb
  app/assets/stylesheets/building_map.scss
  app/controllers/building_map_controller.rb
  app/helpers/routing_helper.rb
  app/views/building_map/index.html.erb
  spec/features/building_map_spec.rb
  spec/helpers/routing_helper_spec.rb
Labels: TF

#86 Feature/apmw 43 refactoring of pr29
  app/controllers/openingtimes_controller.rb
  app/models/building.rb
  app/models/openingtime.rb
  app/models/room.rb
  app/views/devise/registrations/edit.html.erb
  app/views/openingtimes/_form.html.erb
  db/migrate/20211209145340_drop_contact_person_from_room.rb
  db/migrate/20211210125451_change_floor_to_integer_from_room.rb
  db/schema.rb
  spec/factories/openingtimes.rb
  spec/factories/rooms.rb
  spec/helpers/buildings_helper_spec.rb
  spec/helpers/openingtimes_helper_spec.rb
  spec/helpers/rooms_helper_spec.rb
  spec/helpers/users_helper_spec.rb
  spec/models/room_spec.rb
  spec/requests/buildings_spec.rb
  spec/requests/openingtimes_spec.rb
  spec/requests/rooms_spec.rb
  spec/requests/users_spec.rb
  spec/routing/users_routing_spec.rb
  spec/views/openingtimes/edit.html.erb_spec.rb
  spec/views/openingtimes/index.html.erb_spec.rb
  spec/views/openingtimes/new.html.erb_spec.rb
  spec/views/openingtimes/show.html.erb_spec.rb
  spec/views/rooms/edit.html.erb_spec.rb
  spec/views/rooms/index.html.erb_spec.rb
  spec/views/rooms/new.html.erb_spec.rb
  spec/views/rooms/show.html.erb_spec.rb
  spec/views/users/show.html.erb_spec.rb
Labels: APMW

#91 Add Useres as Search Results for Search Bar
  app/controllers/search_results_controller.rb
Labels: CMJD

#87 refactor code of #48 #49
  app/controllers/building_map_controller.rb
  app/helpers/building_map_helper.rb
  app/helpers/routing_helper.rb
  app/views/building_map/index.html.erb
  spec/features/building_map_spec.rb
  spec/helpers/routing_helper_spec.rb
Labels: TF

#93 Feature/rh 16 testing person edit page
  app/controllers/people_controller.rb
  app/views/people/_form.html.erb
  spec/features/people/edit_person_details_spec.rb
Labels: RH

#89 Feature/rh 58 connect search map
  app/assets/images/pin.png
  app/assets/stylesheets/building_map.scss
  app/controllers/building_map_controller.rb
  app/helpers/building_map_helper.rb
  app/helpers/routing_helper.rb
  app/views/building_map/index.html.erb
  app/views/buildings/show.html.erb
  app/views/people/_form.html.erb
  app/views/people/show.html.erb
  app/views/rooms/_form.html.erb
  app/views/rooms/show.html.erb
  spec/features/building_map_spec.rb
  spec/features/people/edit_person_details_spec.rb
  spec/views/buildings/show.html.erb_spec.rb
  spec/views/rooms/show.html.erb_spec.rb
Labels: RH

#88 Feature/rh 57 central UI and navigation
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/building_map.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/components/_topbar.scss
  app/controllers/welcome_controller.rb
  app/helpers/application_helper.rb
  app/views/devise/registrations/edit.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/_topbar.html.erb
  app/views/layouts/application.html.erb
  app/views/welcome/index.html.erb
  app/views/welcome/login.html.erb
  app/views/welcome/protected.html.erb
  config/routes.rb
  spec/features/building_map_spec.rb
  spec/features/home_spec.rb
  spec/features/users/openid_connect_sign_in_spec.rb
Labels: RH

#94 Merge Feature/rh 47
  app/controllers/openingtimes_controller.rb
  app/views/people/_form.html.erb
  spec/features/people/edit_person_details_spec.rb
  spec/models/openingtime_spec.rb
  spec/requests/openingtimes_spec.rb
Labels: RH

#98 Fix #96
  app/controllers/search_results_controller.rb
Labels: APMW
