Repository hpi-swt2/compass-portal-blue, pull requests merged in 2022-01, with the labels that each got.

#102 Feature/tobias 52 navigation between places
  app/assets/constants/places.rb
  app/assets/stylesheets/building_map.scss
  app/controllers/building_map_controller.rb
  app/helpers/building_map_helper.rb
  app/helpers/routing_helper.rb
  app/views/building_map/index.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/application.html.erb
  config/application.rb
  spec/features/building_map_spec.rb
  spec/helpers/routing_helper_spec.rb
Labels: TF

#106 Feature/hg 76 indoor rooms on map
  app/assets/images/lecture-hall-building.geojson
  app/assets/stylesheets/building_map.scss
  app/views/building_map/index.html.erb
Labels: HG

#97 Feature/apmw 54 edit special locations
  app/assets/constants/buildings.rb
  app/assets/constants/locations.rb
  app/assets/images/default-location-photo.png
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/locations.scss
  app/controllers/locations_controller.rb
  app/helpers/locations_helper.rb
  app/models/location.rb
  app/models/openingtime.rb
  app/views/locations/_form.html.erb
  app/views/locations/edit.html.erb
  app/views/locations/index.html.erb
  app/views/locations/new.html.erb
  app/views/locations/show.html.erb
  app/views/people/_form.html.erb
  config/application.rb
  config/routes.rb
  db/migrate/20211209094501_create_locations.rb
  db/migrate/20211209132545_add_additional_fields_to_location.rb
  db/schema.rb
  package-lock.json
  package.json
  spec/factories/locations.rb
  spec/features/locations/edit_spec.rb
  spec/features/locations/index_spec.rb
  spec/features/locations/new_spec.rb
  spec/features/locations/show_spec.rb
  spec/helpers/locations_helper_spec.rb
  spec/models/building_spec.rb
  spec/models/location_spec.rb
  spec/models/openingtime_spec.rb
  spec/requests/locations_spec.rb
  spec/routing/locations_routing_spec.rb
  spec/views/locations/edit.html.erb_spec.rb
  spec/views/locations/index.html.erb_spec.rb
  spec/views/locations/new.html.erb_spec.rb
  spec/views/locations/show.html.erb_spec.rb
  yarn.lock
Labels: APMW

#145 Feature/rh 130 office hours on person show page
  app/models/openingtime.rb
  app/views/people/_form.html.erb
  app/views/people/show.html.erb
  spec/features/people/show_person_details_spec.rb
Labels: RH

#143 Link new person and new locaiton in user edit page
  app/assets/stylesheets/users.scss
  app/views/devise/registrations/edit.html.erb
Labels: APMW

#144 Close #99
  app/views/people/_form.html.erb
Labels: APMW

#142 Feature/apmw_62_locations_via_search
  app/assets/images/location.png
  app/controllers/search_results_controller.rb
  app/views/search_results/index.html.erb
  spec/features/search_result_query_spec.rb
Labels: APMW

#137 Refactoring/tobias 117 convert leaflet to js
  .github/workflows/test_and_deploy.yml
  Gemfile
  Gemfile.lock
  app/assets/constants/buildings.rb
  app/assets/constants/locations.rb
  app/assets/stylesheets/application.scss
  app/controllers/building_map_controller.rb
  app/helpers/building_map_helper.rb
  app/helpers/routing_helper.rb
  app/javascript/packs/application.js
  app/javascript/packs/building_map.js
  app/javascript/packs/leafletMap.js
  app/views/building_map/index.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/locations/show.html.erb
  config/initializers/leaflet.rb
  config/routes.rb
  spec/features/building_map_spec.rb
Labels: TF

#147 Add locateable module
  app/models/building.rb
  app/models/concerns/locateable.rb
  app/models/location.rb
Labels: APMW

#165 Feature/rh 131 update show pages
  app/assets/stylesheets/devise.scss
  app/assets/stylesheets/locations.scss
  app/assets/stylesheets/people.scss
  app/views/buildings/show.html.erb
  app/views/locations/show.html.erb
  app/views/people/_form.html.erb
  app/views/people/show.html.erb
  app/views/rooms/show.html.erb
Labels: RH

#153 Feature/rh 127 single page layout
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/building_map.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/components/_topbar.scss
  app/assets/stylesheets/devise.scss
  app/assets/stylesheets/locations.scss
  app/assets/stylesheets/people.scss
  app/controllers/building_map_controller.rb
  app/helpers/application_helper.rb
  app/helpers/building_map_helper.rb
  app/helpers/routing_helper.rb
  app/javascript/packs/ajax.js
  app/javascript/packs/application.js
  app/javascript/packs/building_map.js
  app/javascript/packs/constants.js
  app/javascript/packs/leafletMap.js
  app/views/building_map/_index.html.erb
  app/views/building_map/_navigationForm.erb
  app/views/building_map/index.html.erb
  app/views/buildings/_form.html.erb
  app/views/buildings/show.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/_topbar.html.erb
  app/views/layouts/application.html.erb
  app/views/locations/_form.html.erb
  app/views/locations/show.html.erb
  app/views/people/_form.html.erb
  app/views/people/show.html.erb
  app/views/rooms/show.html.erb
  app/views/welcome/index.html.erb
  config/routes.rb
  spec/features/building_map_spec.rb
  spec/features/home_spec.rb
  spec/features/people/show_person_details_spec.rb
  spec/features/users/edit_user_details_spec.rb
  spec/helpers/routing_helper_spec.rb
  spec/requests/building_map_spec.rb
  spec/views/buildings/show.html.erb_spec.rb
  spec/views/rooms/show.html.erb_spec.rb
Labels: RH

#157 updated design for passwords and login/signup pages
  app/assets/stylesheets/users.scss
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
Labels: APMW

#161 Improve design for internal pages 2
  app/assets/stylesheets/rooms.scss
  app/assets/stylesheets/users.scss
  app/controllers/buildings_controller.rb
  app/controllers/locations_controller.rb
  app/controllers/openingtimes_controller.rb
  app/controllers/people_controller.rb
  app/controllers/rooms_controller.rb
  app/models/room.rb
  app/views/buildings/_form.html.erb
  app/views/buildings/edit.html.erb
  app/views/buildings/index.html.erb
  app/views/buildings/show.html.erb
  app/views/locations/_form.html.erb
  app/views/locations/edit.html.erb
  app/views/locations/index.html.erb
  app/views/locations/show.html.erb
  app/views/openingtimes/_form.html.erb
  app/views/openingtimes/edit.html.erb
  app/views/openingtimes/index.html.erb
  app/views/openingtimes/show.html.erb
  app/views/people/_form.html.erb
  app/views/people/edit.html.erb
  app/views/people/index.html.erb
  app/views/people/show.html.erb
  app/views/rooms/_form.html.erb
  app/views/rooms/edit.html.erb
  app/views/rooms/index.html.erb
  app/views/rooms/show.html.erb
  db/seeds.rb
  spec/requests/buildings_spec.rb
  spec/requests/locations_spec.rb
  spec/requests/openingtimes_spec.rb
  spec/requests/people_spec.rb
  spec/requests/rooms_spec.rb
  spec/views/openingtimes/edit.html.erb_spec.rb
  spec/views/openingtimes/new.html.erb_spec.rb
  spec/views/rooms/edit.html.erb_spec.rb
  spec/views/rooms/index.html.erb_spec.rb
  spec/views/rooms/new.html.erb_spec.rb
  spec/views/rooms/show.html.erb_spec.rb
Labels: APMW

#182 Fix indoor map being shown on page load
  app/javascript/packs/leafletMap.js
Labels: HG

#152 Feature/TOBIAS 118 Report user location to server
  .github/workflows/test_and_deploy.yml
  Gemfile
  Gemfile.lock
  app/assets/images/current-location.svg
  app/assets/stylesheets/components/_topbar.scss
  app/controllers/users/geo_locations_controller.rb
  app/javascript/packs/building_map.js
  app/javascript/packs/leafletMap.js
  app/javascript/packs/utils.js
  app/models/user.rb
  app/views/layouts/_topbar.html.erb
  config/routes.rb
  spec/features/building_map_spec.rb
  spec/rails_helper.rb
  spec/requests/user_geolocation_spec.rb
Labels: T.O.B.I.A.S.

#202 Feature/rh_179_adding_rooms
  app/views/devise/registrations/edit.html.erb
  spec/features/users/edit_user_details_spec.rb
Labels: RH

#162 Feature/apmw 120 permission with ccc
  Gemfile
  Gemfile.lock
  app/controllers/buildings_controller.rb
  app/controllers/locations_controller.rb
  app/controllers/people_controller.rb
  app/controllers/rooms_controller.rb
  app/models/ability.rb
  app/models/building.rb
  app/models/location.rb
  app/models/person.rb
  app/models/room.rb
  app/models/user.rb
  app/views/buildings/index.html.erb
  app/views/buildings/new.html.erb
  app/views/locations/index.html.erb
  app/views/locations/new.html.erb
  app/views/openingtimes/index.html.erb
  app/views/openingtimes/new.html.erb
  app/views/people/index.html.erb
  app/views/people/new.html.erb
  app/views/rooms/index.html.erb
  app/views/rooms/new.html.erb
  db/migrate/20220109224314_add_admin_to_user.rb
  db/migrate/20220124211929_create_join_table_location_owner.rb
  db/migrate/20220124212152_create_join_table_building_owner.rb
  db/migrate/20220125153503_create_join_tablele_person_owner.rb
  db/migrate/20220126162613_create_join_table_room_owner.rb
  db/schema.rb
  spec/features/locations/edit_spec.rb
  spec/features/locations/index_spec.rb
  spec/features/locations/new_spec.rb
  spec/features/locations/show_spec.rb
  spec/features/people/edit_person_details_spec.rb
  spec/features/people/show_person_details_spec.rb
  spec/features/users/user_authorization_spec.rb
  spec/rails_helper.rb
  spec/requests/buildings_spec.rb
  spec/requests/locations_spec.rb
  spec/requests/people_spec.rb
  spec/requests/rooms_spec.rb
  spec/views/buildings/edit.html.erb_spec.rb
  spec/views/buildings/index.html.erb_spec.rb
  spec/views/buildings/show.html.erb_spec.rb
Labels: APMW

#203 Fix/rh 176 show updated profile picture
  app/views/people/_form.html.erb
  spec/features/people/edit_person_details_spec.rb
Labels: RH
