Repository hpi-swt2/compass-portal-blue, pull requests merged in 2022-02, with the labels that each got.

#204 Feature/rh 180_email_and_tel_clickable
  app/helpers/people_helper.rb
  app/javascript/packs/ajax.js
  app/models/person.rb
  app/views/people/index.html.erb
  app/views/people/show.html.erb
  spec/features/people/show_person_details_spec.rb
  spec/helpers/people_helper_spec.rb
Labels: RH

#227 TOBIAS #201 "Save building polygons as GeoJSON"
  app/assets/constants/buildings.rb
  app/assets/constants/places.rb
  app/assets/geojsons/buildings.geojson
  app/assets/stylesheets/_colors.scss
  app/assets/stylesheets/building_map.scss
  app/controllers/building_map_controller.rb
  app/helpers/building_map_helper.rb
  app/javascript/packs/leafletMap.js
  config/application.rb
  config/routes.rb
Labels: T.O.B.I.A.S.

#198 Feature/tobias 51 indoor navigation
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/assets/constants/indoor_graphs.rb
  app/assets/constants/locations.rb
  app/assets/graphs/ABC.json
  app/assets/graphs/G.json
  app/assets/graphs/H.json
  app/assets/graphs/HS.json
  app/controllers/building_map_controller.rb
  app/helpers/building_map_helper.rb
  app/helpers/dijkstra_helper.rb
  app/helpers/indoor_routing_helper.rb
  app/helpers/outdoor_routing_helper.rb
  app/helpers/routing_helper.rb
  app/javascript/packs/building_map.js.erb
  app/javascript/packs/leafletMap.js.erb
  config/application.rb
  spec/features/building_map_spec.rb
  spec/helpers/outdoor_routing_helper_spec.rb
  spec/helpers/routing_helper_spec.rb
  spec/requests/building_map_spec.rb
Labels: T.O.B.I.A.S.

#194 Follow ups to #152 "Report user position to server"
  Gemfile
  app/controllers/users/geo_locations_controller.rb
  app/javascript/packs/building_map.js.erb
  app/javascript/packs/utils.js
  app/models/user.rb
  app/views/layouts/_topbar.html.erb
  app/views/layouts/application.html.erb
  spec/models/user_spec.rb
  spec/requests/user_geolocation_spec.rb
Labels: T.O.B.I.A.S.

#205 Feature/rh 129 hide person user difference
  app/controllers/application_controller.rb
  app/models/user.rb
  app/views/devise/registrations/edit.html.erb
  app/views/people/_form.html.erb
  app/views/people/_form_fields.html.erb
  spec/features/users/edit_user_details_spec.rb
Labels: RH

#239 Feature/apmw 168 locations floors
  app/javascript/packs/ajax.js
  app/javascript/packs/building_map.js.erb
  app/views/rooms/show.html.erb
Labels: APMW

#257 Fix/apmw 212 3 additional import fixes for production
  app/assets/stylesheets/application.scss
Labels: bug, APMW

#247 Unifies naming in geojson
  app/assets/geojsons/HS_-1.geojson
  app/assets/geojsons/HS_0.geojson
  app/assets/geojsons/H_0.geojson
  app/assets/geojsons/H_1.geojson
  app/assets/geojsons/H_2.geojson
  app/assets/geojsons/H_3.geojson
Labels: HG

#261 Hotfix for current dev
  app/assets/geojsons/V_0.geojson
  spec/rails_helper.rb
Labels: T.O.B.I.A.S., HG, fix

#260 Feature/tobias indoor navigation buildings V and E
  app/assets/constants/indoor_graphs.rb
  app/assets/graphs/V-E.json
  app/helpers/building_map_helper.rb
  app/helpers/routing_helper.rb
Labels: T.O.B.I.A.S.

#264 Fix: Mobile friendly position tracking switch
  app/assets/stylesheets/components/_topbar.scss
  app/views/layouts/_topbar.html.erb
Labels: T.O.B.I.A.S.

#269 Feature/cmjd 123 translation of code
  app/controllers/buildings_controller.rb
  app/controllers/events_controller.rb
  app/controllers/locations_controller.rb
  app/controllers/openingtimes_controller.rb
  app/controllers/people_controller.rb
  app/controllers/rooms_controller.rb
  app/javascript/packs/leafletMap.js.erb
  app/models/event.rb
  app/models/person.rb
  app/models/room.rb
  app/views/buildings/_form.html.erb
  app/views/buildings/edit.html.erb
  app/views/buildings/index.html.erb
  app/views/buildings/new.html.erb
  app/views/buildings/show.html.erb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/events/_form.html.erb
  app/views/events/edit.html.erb
  app/views/events/index.html.erb
  app/views/events/new.html.erb
  app/views/events/show.html.erb
  app/views/layouts/_topbar.html.erb
  app/views/layouts/application.html.erb
  app/views/locations/_form.html.erb
  app/views/locations/edit.html.erb
  app/views/locations/index.html.erb
  app/views/locations/new.html.erb
  app/views/locations/show.html.erb
  app/views/openingtimes/_form.html.erb
  app/views/openingtimes/edit.html.erb
  app/views/openingtimes/index.html.erb
  app/views/openingtimes/new.html.erb
  app/views/openingtimes/show.html.erb
  app/views/people/_form_fields.html.erb
  app/views/people/edit.html.erb
  app/views/people/index.html.erb
  app/views/people/new.html.erb
  app/views/people/show.html.erb
  app/views/rooms/_form.html.erb
  app/views/rooms/edit.html.erb
  app/views/rooms/index.html.erb
  app/views/rooms/new.html.erb
  app/views/rooms/show.html.erb
  app/views/search_results/index.html.erb
  app/views/welcome/index.html.erb
  app/views/welcome/login.html.erb
  config/locales/de.yml
  config/locales/en.yml
  spec/features/users/edit_user_details_spec.rb
  spec/requests/events_spec.rb
Labels: CMJD

#274 remove duplicate and add fallback
  app/views/buildings/show.html.erb
  app/views/locations/show.html.erb
Labels: fix
